name: Deploy SDK

permissions:
  contents: write # Required to create the GitHub Release

on:
  push:
    tags:
      - "v*" # Triggers on tags like v0.1.0, v1.0.0
  workflow_dispatch:

jobs:
  # --- JOB 1: BUILD ---
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Build SDK
        run: poetry build

      # Save the built files (dist folder) to be used by the next jobs
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdk-dist
          path: dist/*

  # --- JOB 2: GITHUB RELEASE ---
  gh-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: sdk-dist
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # This attaches the .whl and .tar.gz to the GitHub Release page
          files: dist/*
          generate_release_notes: true

  # --- JOB 3: PYPI PUBLISH ---
  pypi-publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: sdk-dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist/
          password: ${{ secrets.PYPI_SDK_TOKEN }}